#### 【 이미지 연산 】

- Numpy 방식 : 관심영역 설정
    * 픽셀의 값 범위 0 ~ 255로 제한 코드 직접 작성

- CV2 함수 방식
    * cv2.add() / substract() / division() : 내부에서 처리

- ★★★ 주의 : opencv의 채널 순서가 BGR로 일반 이미지 순서와 다름

[1] 모듈 로딩 및 데이터 준비 <hr>

In [ ]:
## [1-1] 모듈로딩
import cv2
import matplotlib.pyplot as plt

In [ ]:
## [1-2] 데이터 준비
IMG_FILE = '../Data/Image/cat_01.jpg'

[2] 데이터 로딩 <hr>

In [1]:
import cv2
import numpy as np

a = np.uint8([[200, 50]])
b = np.uint8([[100, 100]])

add1 = a + b
sub1 = a - b
mult1 = a * 2
div1 = a / 3

add2 = cv2.add(a, b)
sub2 = cv2.subtract(a, b)
mult2 = cv2.multiply(a, 2)
div2 = cv2.divide(a, 3)

print(add1, add2)
print(sub1, sub2)
print(mult1, mult2)
print(div1, div2)

[[ 44 150]] [[255 150]]
[[100 206]] [[100   0]]
[[144 100]] [[255 100]]
[[66.66666667 16.66666667]] [[67 17]]


[2] 이미지 픽셀 누적 연산 <hr>

In [2]:
a = np.array([[1, 2]], dtype=np.uint8)
b = np.array([[10, 20]], dtype=np.uint8)

mask = np.array([[1, 0]], dtype=np.uint8)

c1 = cv2.add( a, b, None, mask)
print(c1)
c2 = cv2.add( a, b, b, mask)
print(c2)

[[11  0]]
[[11 20]]


In [ ]:
## [3-1] 컬러 이미지 밝기 조절
#### 
numObj = [oriNP, ]