#### 【 이미지 연산 】

- 픽셀(Pixel) 연산 수행 이미지 변화
    * 이미지데이터 => 행열, Numpy의 ndarray
    * 덧__셈 연산 => 각각의 픽셀 단위 덧셈
    * 뺄__셈 연산 => 각각의 픽셀 단위 뺄셈
    * 곱__셈 연산 => 각각의 픽셀 단위 곱셈
    * 나눗셈 연산 => 각각의 픽셀 단위 나눗셈
- 색상값 : 0 검정색 Black - 1 또는 255 흰색 White
    * 0 >>>>>>> 1 또는 255 : 밝아짐
    * 0 <<<<<<< 1 또는 255 : 어두워짐
- 이미지 밝기 조절
- 이미지 자연스러운 합성

[1] 이미지 픽셀 기본 연산 <hr>

In [1]:
import cv2
import numpy as np

a = np.uint8([[200, 50]])
b = np.uint8([[100, 100]])

add1 = a + b
sub1 = a - b
mult1 = a * 2
div1 = a / 3

add2 = cv2.add(a, b)
sub2 = cv2.subtract(a, b)
mult2 = cv2.multiply(a, 2)
div2 = cv2.divide(a, 3)

print(add1, add2)
print(sub1, sub2)
print(mult1, mult2)
print(div1, div2)

[[ 44 150]] [[255 150]]
[[100 206]] [[100   0]]
[[144 100]] [[255 100]]
[[66.66666667 16.66666667]] [[67 17]]


[2] 이미지 픽셀 누적 연산 <hr>

In [2]:
a = np.array([[1, 2]], dtype=np.uint8)
b = np.array([[10, 20]], dtype=np.uint8)

mask = np.array([[1, 0]], dtype=np.uint8)

c1 = cv2.add( a, b, None, mask)
print(c1)
c2 = cv2.add( a, b, b, mask)
print(c2)

[[11  0]]
[[11 20]]


In [ ]:
## [3-1] 컬러 이미지 밝기 조절
#### 
numObj = [oriNP, ]