### [2025_12_09]_데이터 전처리
* 피쳐들 타입에 따른 전처리
  - 범주형피쳐 : 명목형/순서형 => 인코딩
	* -> 명목형 => OneHotEncoding
	* -> 순서형 => OrdinalEncoding
  - 수치형피쳐
	* -> 범주형 변환 ? : 데이터가 가진 의미 체크
	* -> 수치형 => 스케일링 여부

* 타겟 컬럼에 대한 처리
	- 범주형 => LabelEncoding
	- 수치형 => 그대로

* titanic.csv, auto_mpg.csv

### 인코딩 함수 만들기
- 함수 종류
    * 범주형 (명목형 / 순서형)
    * 수치형

## 범주형
- 명목형
    * OneHotEncoder

In [13]:
def encode_onehot(df, cols):

    from sklearn.preprocessing import OneHotEncoder
    import pandas as pd

    ohEncoder = OneHotEncoder(sparse_output=False)

    ohEncoder.fit(df[cols])

    encoding = ohEncoder.transform(df[cols])

    return encoding

- 순서형
    * OrdinalEncoder

In [21]:
def encode_ordi(df, cols):

    from sklearn.preprocessing import OrdinalEncoder
    import pandas as pd

    ordEncoder = OrdinalEncoder()

    ordEncoder.fit(df[cols])

    encoding = ordEncoder.transform(df[cols])

    return encoding

## 수치형
- 정규 스케일링

In [30]:
def scaling(df, cols):
    from sklearn.preprocessing import StandardScaler

    scaler = StandardScaler()

    scaled_data = scaler.fit_transform(df[cols])

    return scaled_data

In [3]:
## 모듈 불러오기
import pandas as pd
import numpy as np

In [4]:
## 데이터 불러오기
DATA_FILE = '../Data/titanic.csv'

df = pd.read_csv(DATA_FILE)
df.head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

## 컬럼 구분하기
    - 명목형
        * sex
        * embarked
        * who
        * deck
        * embark_town
        * alive
        * adult_male
        * alone
    - 순서형
        * pclass
        * class
    - 수치형
        * age
        * sibsp
        * parch
        * fare
    
    - 타켓 컬럼
        * survived
    
    

In [25]:
# who : sex+age랑 중복이라 드롭
# deck : 결측치 많으니 드롭
# embark_town : embarked와 중복이라 드롭
# alive : survived와 동일이라 드롭
# adult_male :sex+age와 중복이라 드롭
s1 = encode_onehot(df, ['sex', 'embarked', 'alone'])
print(s1)

[[0. 1. 0. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 1.]]


In [26]:
# class : pclass와 중복이라 드롭
s2 = encode_ordi(df, ['pclass'])
print(s2)

[[2.]
 [0.]
 [2.]
 [0.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [1.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [2.]
 [1.]
 [1.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [0.]
 [0.]
 [2.]
 [1.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [2.]
 [1.]
 [2.]
 [2.]
 [0.]
 [0.]
 [2.]
 [0.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [1.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [0.]
 [1.]
 [1.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [0.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [2.]
 [2.]
 [1.]
 [1.]
 [1.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.

In [32]:
s3 = scaling(df, ['age', 'sibsp', 'parch', 'fare'])