### [2025_12_09]_데이터 전처리
* 피쳐들 타입에 따른 전처리
  - 범주형피쳐 : 명목형/순서형 => 인코딩
	* -> 명목형 => OneHotEncoding
	* -> 순서형 => OrdinalEncoding
  - 수치형피쳐
	* -> 범주형 변환 ? : 데이터가 가진 의미 체크
	* -> 수치형 => 스케일링 여부

* 타겟 컬럼에 대한 처리
	- 범주형 => LabelEncoding
	- 수치형 => 그대로

* titanic.csv, auto_mpg.csv

### 인코딩 함수 만들기
- 함수 종류
    * 범주형 (명목형 / 순서형)
    * 수치형

## 범주형
- 명목형
    * OneHotEncoder

In [13]:
def encode_onehot(df, cols):

    from sklearn.preprocessing import OneHotEncoder
    import pandas as pd

    ohEncoder = OneHotEncoder(sparse_output=False)

    ohEncoder.fit(df[cols])

    encoding = ohEncoder.transform(df[cols])

    return encoding

- 순서형
    * OrdinalEncoder

In [21]:
def encode_ordi(df, cols):

    from sklearn.preprocessing import OrdinalEncoder
    import pandas as pd

    ordEncoder = OrdinalEncoder()

    ordEncoder.fit(df[cols])

    encoding = ordEncoder.transform(df[cols])

    return encoding

## 수치형
- 정규 스케일링

In [30]:
def scaling(df, cols):
    from sklearn.preprocessing import StandardScaler

    scaler = StandardScaler()

    scaled_data = scaler.fit_transform(df[cols])

    return scaled_data

In [3]:
## 모듈 불러오기
import pandas as pd
import numpy as np

In [4]:
## 데이터 불러오기
DATA_FILE = '../Data/titanic.csv'

df = pd.read_csv(DATA_FILE)
df.head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

## 컬럼 구분하기
    - 명목형
        * sex
        * embarked
        * who
        * deck
        * embark_town
        * alive
        * adult_male
        * alone
    - 순서형
        * pclass
        * class
    - 수치형
        * age
        * sibsp
        * parch
        * fare
    
    - 타켓 컬럼
        * survived
    
    

In [25]:
# who : sex+age랑 중복이라 드롭
# deck : 결측치 많으니 드롭
# embark_town : embarked와 중복이라 드롭
# alive : survived와 동일이라 드롭
# adult_male :sex+age와 중복이라 드롭
s1 = encode_onehot(df, ['sex', 'embarked', 'alone'])
print(s1)

[[0. 1. 0. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 1.]]


In [26]:
# class : pclass와 중복이라 드롭
s2 = encode_ordi(df, ['pclass'])
print(s2)

[[2.]
 [0.]
 [2.]
 [0.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [1.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [2.]
 [1.]
 [1.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [0.]
 [0.]
 [2.]
 [1.]
 [0.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [2.]
 [1.]
 [2.]
 [2.]
 [0.]
 [0.]
 [2.]
 [0.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [1.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [0.]
 [1.]
 [1.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [0.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [2.]
 [2.]
 [1.]
 [1.]
 [1.]
 [0.]
 [2.]
 [2.]
 [2.]
 [0.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [0.

In [32]:
s3 = scaling(df, ['age', 'sibsp', 'parch', 'fare'])

In [ ]:
titanic = np.concatenate((s1, s2, s3), axis=1)

array([[ 0.        ,  1.        ,  0.        , ...,  0.43279337,
        -0.47367361, -0.50244517],
       [ 1.        ,  0.        ,  1.        , ...,  0.43279337,
        -0.47367361,  0.78684529],
       [ 1.        ,  0.        ,  0.        , ..., -0.4745452 ,
        -0.47367361, -0.48885426],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.43279337,
         2.00893337, -0.17626324],
       [ 0.        ,  1.        ,  1.        , ..., -0.4745452 ,
        -0.47367361, -0.04438104],
       [ 0.        ,  1.        ,  0.        , ..., -0.4745452 ,
        -0.47367361, -0.49237783]], shape=(891, 13))

# Auto_mpg 파일

In [36]:
DATA_FILE2 = '../Data/auto_mpg.csv'

df2 = pd.read_csv(DATA_FILE2)
df2.head(3)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite

In [54]:
df2.info() # horsepower object 타입 변환시켜주기
df2['horsepower'] = pd.to_numeric(df2['horsepower'], errors='coerce')
df2['horsepower'] = df2['horsepower'].astype(float)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(4), int64(4), object(1)
memory usage: 28.1+ KB


## 컬럼 구분하기
    - 명목형
        * origin
    - 순서형
        * model year
    - 수치형
        * mpg
        * cylinders
        * displacement
        * horsepower
        * weight
        * acceleration
    
    - 타켓 컬럼
        * 
    
    

In [56]:
a1 = encode_onehot(df2, ['origin'])
print(a1)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [57]:
a2 = encode_ordi(df2, ['model year'])
print(a2)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 4.]

In [58]:
a3 = scaling(df2, ['mpg', 'cylinders', 'displacement', 'weight', 'acceleration'])
print(a3)

[[-0.7064387   1.49819126  1.0906037   0.63086987 -1.29549834]
 [-1.09075062  1.49819126  1.5035143   0.85433297 -1.47703779]
 [-0.7064387   1.49819126  1.19623199  0.55047045 -1.65857724]
 ...
 [ 1.08701694 -0.85632057 -0.56103873 -0.79858454 -1.4407299 ]
 [ 0.57460104 -0.85632057 -0.70507731 -0.40841088  1.10082237]
 [ 0.95891297 -0.85632057 -0.71467988 -0.29608816  1.39128549]]


In [59]:
autompg = np.concatenate((a1, a2, a3), axis=1)
print(autompg)

[[ 1.          0.          0.         ...  1.0906037   0.63086987
  -1.29549834]
 [ 1.          0.          0.         ...  1.5035143   0.85433297
  -1.47703779]
 [ 1.          0.          0.         ...  1.19623199  0.55047045
  -1.65857724]
 ...
 [ 1.          0.          0.         ... -0.56103873 -0.79858454
  -1.4407299 ]
 [ 1.          0.          0.         ... -0.70507731 -0.40841088
   1.10082237]
 [ 1.          0.          0.         ... -0.71467988 -0.29608816
   1.39128549]]
