【 Numpy - Array 생성 】<hr>

In [ ]:
## 모듈 로딩
import numpy as np          ## 이밎 데이터 저장 관련 모듈
import cv2                  ## opencv 패키지

In [ ]:
## ==============================================
## Image ==> 로딩 : ndarray 데이터
## ==============================================
## 이미지 파일
IMG_FILE = '../Data/Image/blackpink.jpg'

## 이미지 데이터 로딩 : cv2.imread(이미지파일경로_문자열)
imgNP = cv2.imread(IMG_FILE)

## 이미지 로우 데이터 정보 출력
print(f'이미지 로우 데이터 정보 => {imgNP.shape} , {imgNP.ndim}D차원')

array([4.88310304e+233, 1.84911460e-286])

In [5]:
## 초기화 => 값 넣기
a1.fill(255)
a1

array([[255., 255., 255., 255.],
       [255., 255., 255., 255.],
       [255., 255., 255., 255.]])

In [8]:
## ==============================================
## 0으로 채운 array 객체 생성
## ==============================================
## => float64 기본
a1 = np.ones((2,3))
print(a1.dtype, a1, sep='\n')

## => int8 설정
a1 = np.ones((2,3), dtype=np.int8)
print(a1.dtype, a1, sep='\n')

## => bool 설정
a1 = np.ones((2,3), dtype=np.bool)
print(a1.dtype, a1, sep='\n')

float64
[[1. 1. 1.]
 [1. 1. 1.]]
int8
[[1 1 1]
 [1 1 1]]
bool
[[ True  True  True]
 [ True  True  True]]
