【 Numpy - Array 생성 】<hr>

In [ ]:
## 모듈 로딩
import numpy as np          ## 이미지 데이터 저장 관련 모듈
import cv2                  ## opencv 패키지

In [ ]:
## ==============================================
## 빈 array 객체 생성
## ==============================================
## 원하는 형태의 메모리 공간 할당. 초기화 안 됨!
a1=np.empty((3, 4))
a2=np.empty(2)
a2

array([4.88310304e+233, 1.84911460e-286])

In [5]:
## 초기화 => 값 넣기
a1.fill(255)
a1

array([[255., 255., 255., 255.],
       [255., 255., 255., 255.],
       [255., 255., 255., 255.]])

In [8]:
## ==============================================
## 0으로 채운 array 객체 생성
## ==============================================
## => float64 기본
a1 = np.ones((2,3))
print(a1.dtype, a1, sep='\n')

## => int8 설정
a1 = np.ones((2,3), dtype=np.int8)
print(a1.dtype, a1, sep='\n')

## => bool 설정
a1 = np.ones((2,3), dtype=np.bool)
print(a1.dtype, a1, sep='\n')

float64
[[1. 1. 1.]
 [1. 1. 1.]]
int8
[[1 1 1]
 [1 1 1]]
bool
[[ True  True  True]
 [ True  True  True]]
