#### 【 이미지 기계학습 】

- 이미지 전처리
    * 입력 형태를 맞추는 전처리는 모두 동일 적용
    * 분포를 흔드는 랜덤 변환은 train만 적용
    * train/valid/test 모두 적용
        - 리사이징, 크롭, 배경 제거, 색공간 변경, 픽셀 스케일링 변경
    * train만 진행
        - 데이터 증강용 작업 : Random flip, Random rotation, Color jitter ㅡ Noise 추가  


[1] 모듈 로딩 및 데이터 준비<hr>

In [4]:
## =================================================================
## [1-1] 모듈 로딩
## =================================================================
##- 기본 모듈
import numpy as np
import pandas as pd

##- ML 데이터셋 관련 
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

##- ML 학습 알고리즘 관련
from sklearn.linear_model import LogisticRegression

##- ML 성능지표 관련
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [5]:
## =================================================================
## [1-2] 데이터 준비
## =================================================================
##- 데이터 설정
CSV_PATH = "../Data/MNIST/mnist_train.csv"

##- 데이터 로딩 
mnistDF  = pd.read_csv(CSV_PATH, header=None)   

[2] 피쳐와 타겟 & 학습용과 테스트용 데이터셋 준비<hr>

In [6]:
## =====================================================
## [2-1] 첫 컬럼: 라벨, 나머지 784개: 픽셀(28x28)
## =====================================================
y = mnistDF.iloc[:, 0].astype(np.int64).values
X = mnistDF.iloc[:, 1:].astype(np.float32).values

print("X shape:", X.shape, "y shape:", y.shape)  # (N, 784), (N,)

X shape: (10001, 784) y shape: (10001,)


In [7]:
## =====================================================
## [2-2] train/test 분리
## =====================================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


[3] 교차검증 통한 하이퍼파라미터 찾기<hr>

In [8]:
# =========================================================
# [3-1] Pipeline (누수 방지: PCA는 CV fold의 train에서만 fit)
# =========================================================
pipe = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("pca",    PCA(random_state=42)),
    ("clf",    LogisticRegression(max_iter=3000,solver="lbfgs" ))
])

In [9]:
# =========================================================
# [3-2] 교차검증 위한 학습 모델 하이퍼라라미터 
# =========================================================
param_grid = {
    # PCA 차원: 정수(주성분 개수) 또는 누적분산 비율(0~1)
    "pca__n_components": [0.90, 0.95, 0.97, 40, 60, 80, 120],
    # LR 규제 강도(C): 클수록 규제 약함
    "clf__C": [0.1, 1.0, 3.0, 10.0],
}

In [10]:
# =========================================================
# [3-3] 사용자 정의 교차검증 설정
# =========================================================
## 자동 CV는 내부에서 random_state 고정하지 않음 
## 재현성 위해 설정 
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)


In [11]:
## ==========================================================================================
## [3-4] 교차검증
## -> refit 매개변수
##   * refit = True인 경우 : 전체 Train Dataset + 최적 하이퍼파라미터로 학습 후 estimator 반환
##   * refit = False인 경우: X ==> 개발자가 직접
##                                전체 Train Dataset + 최적 하이퍼파라미터로 학습 진행
## ==========================================================================================
grid = GridSearchCV(
    estimator=pipe,
    param_grid=param_grid,
    scoring="accuracy",
    cv=cv,
    verbose=1,
    refit=True
)

grid.fit(X_train, y_train)

print("\n[BEST PARAMS]")
print(grid.best_params_)
print("[BEST CV SCORE]", grid.best_score_)

Fitting 5 folds for each of 28 candidates, totalling 140 fits

[BEST PARAMS]
{'clf__C': 0.1, 'pca__n_components': 120}
[BEST CV SCORE] 0.9063749999999999


[2] PCA만 확인 <hr>

In [16]:
stdScaler = StandardScaler()
scaled_x_train = stdScaler.fit_transform(X_train)
scaled_x_test  = stdScaler.fit(X_test)

print(f'{scaled_x_train}, {scaled_x_test}')

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], StandardScaler()


In [14]:
pca = PCA(random_state=42)
pca_x_train = pca.fit_transform(scaled_x_train)
print(f'pca_x_train : {pca_x_train.shape}')

pca_x_train : (8000, 784)


In [15]:
pca = PCA(random_state=42, n_components=80)

pca_x_train = pca.fit_transform(scaled_x_train)
print(f'pca_x_train : {pca_x_train.shape}')

print(f'n_components_               : {pca.n_components_}')
print(f'n_components_               : {pca.components_}')
print(f'\nexplained_variance_ratio_   : {pca.explained_variance_ratio_}')

pca_x_train : (8000, 80)
n_components_               : 80
n_components_               : [[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]

explained_variance_ratio_   : [0.06200914 0.04354504 0.04098257 0.03090727 0.0272053  0.02375536
 0.02104611 0.01917703 0.01685067 0.01511556 0.01486488 0.01262179
 0.0122248  0.01173976 0.01150695 0.01094878 0.01049989 0.01026026
 0.00971433 0.00950808 0.00933264 0.00877348 0.00871097 0.00847008
 0.00804989 0.00783544 0.00766237 0.00717114 0.00702499 0.00687048
 0.00678905 0.00640243 0.0063644  0.00620449 0.0061186  0.00596362
 0.00591287 0.00576641 0.0055912  0.00552268 0.00525212 0.00518894
 0.00513173 0.00489152 0.00479591 0.00470755 0.00461578 0.00455986
 0.00451392 0.00443915 0.00435593 0.0043162  0.00419301 0.00409138
 0.00404535 0.0040054  0.00395226 0.00391185 0.0038582  0.00378039
 0.00372156 0.00368