#### D1218_파이썬으로 만드는 OpenCV 프로젝트 교과서 과제
- Numpy (55page ~ 87 page)

In [ ]:
# 3.1.1 이미지와 Numpy
import cv2
img = cv2.imread('../Data/Image/blank_500.jpg')
type(img)

numpy.ndarray

In [2]:
img.ndim

3

In [3]:
img.shape

(500, 500, 3)

In [4]:
img.size

750000

In [5]:
img.dtype

dtype('uint8')

In [6]:
img.itemsize

1

In [8]:
# 3.1.3 값으로 생성
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [9]:
a.dtype

dtype('int64')

In [10]:
a.shape

(4,)

In [11]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
b.shape

(2, 4)

In [13]:
c = np.array([1, 2, 3.14, 4])
c

array([1.  , 2.  , 3.14, 4.  ])

In [14]:
c.dtype

dtype('float64')

In [15]:
d = np.array([1,2,3,4], dtype=np.float32)
d

array([1., 2., 3., 4.], dtype=float32)

In [16]:
a = np.uint8([1,2,3,4])

In [17]:
# 3.1.4 크기와 초기 값으로 생성
a=np.empty((2,3))
a

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [4.45037859e-307, 1.42419938e-306, 7.56603881e-307]])

In [18]:
a.dtype

dtype('float64')

In [20]:
a.fill(255)
a

array([[255., 255., 255.],
       [255., 255., 255.]])

In [21]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
b.dtype

dtype('float64')

In [23]:
c=np.zeros((2,3), dtype=np.int8)
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [24]:
d=np.ones((2,3), dtype=np.int16)
d

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [25]:
e=np.full((2,3,4), 255, dtype=np.uint8)
e

array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]]], dtype=uint8)

In [28]:
img = cv2.imread('../Data/Image/girl.jpg')
img

array([[[ 52,  71,  76],
        [ 47,  68,  70],
        [ 39,  69,  64],
        ...,
        [ 24,  72,  54],
        [ 31,  76,  59],
        [ 35,  80,  63]],

       [[ 51,  70,  75],
        [ 47,  68,  70],
        [ 39,  69,  64],
        ...,
        [ 26,  74,  56],
        [ 32,  77,  60],
        [ 35,  80,  63]],

       [[ 51,  70,  73],
        [ 46,  67,  68],
        [ 39,  69,  64],
        ...,
        [ 28,  77,  57],
        [ 33,  78,  61],
        [ 35,  80,  63]],

       ...,

       [[ 29,  95,  66],
        [ 38, 104,  75],
        [ 47, 115,  84],
        ...,
        [218, 190, 203],
        [221, 191, 202],
        [222, 192, 203]],

       [[ 28,  94,  65],
        [ 37, 104,  75],
        [ 47, 117,  86],
        ...,
        [218, 190, 203],
        [222, 192, 203],
        [224, 194, 205]],

       [[ 25,  92,  63],
        [ 36, 103,  74],
        [ 46, 116,  85],
        ...,
        [223, 193, 206],
        [226, 196, 207],
        [229, 199, 210]]

In [29]:
img.shape

(293, 406, 3)

In [30]:
a = np.empty_like(img)
b = np.zeros_like(img)
c = np.ones_like(img)
d = np.full_like(img, 255)
a

array([[[ 64,  32,  20],
        [120, 151,   2],
        [  0,   0,  80],
        ...,
        [119,  68, 111],
        [151,   2,   0],
        [  0, 112, 153]],

       [[ 20, 121, 151],
        [  2,   0,   0],
        [240, 119,  68],
        ...,
        [111, 151,   2],
        [  0,   0, 176],
        [171,  20, 121]],

       [[151,   2,   0],
        [  0, 240, 119],
        [ 68, 111, 151],
        ...,
        [  2,   0,   0],
        [176, 193,  22],
        [121, 151,   2]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [31]:
a.shape

(293, 406, 3)

In [32]:
b

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(293, 406, 3), dtype=uint8)

In [33]:
b.shape

(293, 406, 3)

In [34]:
c

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       ...,

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], shape=(293, 406, 3), dtype=uint8)

In [35]:
c.shape

(293, 406, 3)

In [36]:
d

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [37]:
d.shape

(293, 406, 3)

In [38]:
# 3.1.5 시퀀스와 난수로 생성
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [39]:
a.dtype

dtype('int64')

In [40]:
a.shape

(5,)

In [41]:
b = np.arange(5.0)
b

array([0., 1., 2., 3., 4.])

In [42]:
b.dtype

dtype('float64')

In [43]:
c = np.arange(3,9,2)
c

array([3, 5, 7])

In [44]:
np.random.rand()

0.8252775740694449

In [45]:
a = np.random.rand(2,3)
a

array([[0.74134282, 0.47575017, 0.45487221],
       [0.12133574, 0.5785316 , 0.9320639 ]])

In [46]:
b = np.random.rand(2,3)
b

array([[0.30378722, 0.7785111 , 0.21851074],
       [0.74664794, 0.11827264, 0.04555255]])

In [47]:
# 3.1.6 dtype 변경
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [48]:
a.dtype

dtype('int64')

In [49]:
b = a.astype('float32')
b

array([0., 1., 2., 3., 4.], dtype=float32)

In [50]:
a.dtype

dtype('int64')

In [51]:
c = a.astype(np.float64)
c

array([0., 1., 2., 3., 4.])

In [52]:
c.dtype

dtype('float64')

In [53]:
a.dtype

dtype('int64')

In [54]:
d = np.uint8(a)
d

array([0, 1, 2, 3, 4], dtype=uint8)

In [55]:
# 3.1.7 차원 변경
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [56]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
c = np.reshape(a, (2,3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
d = np.arange(100).reshape(2, -1)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [59]:
d.shape

(2, 50)

In [60]:
e = np.arange(100).reshape(-1, 5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [61]:
e.shape

(20, 5)

In [62]:
f = np.zeros((2,3))
f

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
f.reshape((6,))

array([0., 0., 0., 0., 0., 0.])

In [64]:
f.reshape(-1)

array([0., 0., 0., 0., 0., 0.])

In [65]:
np.ravel(f)

array([0., 0., 0., 0., 0., 0.])

In [66]:
g = np.arange(10).reshape(2,-1)
g

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
g.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [69]:
# 3.1.8 브로드캐스팅 연산
mylist = list(range(10))
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
for i in range(len(mylist)):
    mylist[i] = mylist[i] + 1
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [71]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
a = np.arange(5)

In [74]:
a+5

array([5, 6, 7, 8, 9])

In [75]:
a-2

array([-2, -1,  0,  1,  2])

In [76]:
a*2

array([0, 2, 4, 6, 8])

In [77]:
a/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [78]:
a**2

array([ 0,  1,  4,  9, 16])

In [79]:
b = np.arange(6).reshape(2, -1)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [80]:
b*2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [81]:
a

array([0, 1, 2, 3, 4])

In [82]:
a>2

array([False, False, False,  True,  True])

In [86]:
a = np.arange(10, 60, 10)
b = np.arange(1, 6)
a

array([10, 20, 30, 40, 50])

In [84]:
b

array([1, 2, 3, 4, 5])

In [87]:
a+b

array([11, 22, 33, 44, 55])

In [88]:
a-b

array([ 9, 18, 27, 36, 45])

In [89]:
a*b

array([ 10,  40,  90, 160, 250])

In [90]:
a/b

array([10., 10., 10., 10., 10.])

In [91]:
a**b

array([       10,       400,     27000,   2560000, 312500000])

In [93]:
a = np.ones((2,3))
b = np.ones((3,2))
#a + b

In [94]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [95]:
c = np.arange(3)
c

array([0, 1, 2])

In [96]:
a+c

array([[1., 2., 3.],
       [1., 2., 3.]])

In [98]:
d = np.arange(2)
#a+d

In [99]:
d = np.arange(2).reshape(2,1)
d

array([[0],
       [1]])

In [100]:
a+d

array([[1., 1., 1.],
       [2., 2., 2.]])

In [101]:
# 3.1.9 인덱싱과 슬라이싱
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a[5]

np.int64(5)

In [103]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
b[1]

array([4, 5, 6, 7])

In [105]:
b[1,2]

np.int64(6)

In [106]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
a[5]=9
a

array([0, 1, 2, 3, 4, 9, 6, 7, 8, 9])

In [108]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
b[0]=0
b

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
b[1,2] = 99
b

array([[ 0,  0,  0,  0],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

In [111]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
a[2:5]

array([2, 3, 4])

In [113]:
a[5:]

array([5, 6, 7, 8, 9])

In [114]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
b[0:2, 1]

array([1, 5])

In [117]:
b[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [118]:
b[2, :]

array([ 8,  9, 10, 11])

In [119]:
b[:, 1]

array([1, 5, 9])

In [120]:
b[0:2, 1:3] = 0
b

array([[ 0,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

In [121]:
bb = b[0:2, 1:3]
bb

array([[0, 0],
       [0, 0]])

In [122]:
bb[0]

array([0, 0])

In [123]:
b

array([[ 0,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

In [124]:
# 3.1.10 팬시 인덱싱
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [125]:
a[[1,3]]

array([1, 3])

In [126]:
a[[True, False, True, False, True]]

array([0, 2, 4])

In [127]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
b = a > 5
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [129]:
a[b]

array([6, 7, 8, 9])

In [130]:
a[a>5]

array([6, 7, 8, 9])

In [131]:
a[a>5] = 1
a

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1])

In [132]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
b[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [134]:
b[[0,2], [2,3]]

array([ 2, 11])

In [135]:
# 3.1.11 병합과 분리
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [136]:
b = np.arange(10, 14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [137]:
np.vstack( (a,b) )

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [138]:
np.hstack( (a,b) )

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [139]:
np.concatenate((a,b), 0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [140]:
np.concatenate((a,b), 1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [141]:
a = np.arange(12).reshape(4,3)
b = np.arange(10, 130, 10).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [142]:
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [143]:
c = np.stack( (a,b), 0)
c.shape

(2, 4, 3)

In [144]:
c

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [145]:
d = np.stack( (a,b), 1)
d.shape

(4, 2, 3)

In [146]:
d

array([[[  0,   1,   2],
        [ 10,  20,  30]],

       [[  3,   4,   5],
        [ 40,  50,  60]],

       [[  6,   7,   8],
        [ 70,  80,  90]],

       [[  9,  10,  11],
        [100, 110, 120]]])

In [147]:
e = np.stack( (a,b), 2)
e.shape

(4, 3, 2)

In [148]:
e

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

In [149]:
ee = np.stack( (a,b), -1)
ee.shape

(4, 3, 2)

In [150]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
np.hsplit(a, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [152]:
np.hsplit(a, [3,6])

[array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [153]:
np.hsplit(a, [3,6,9])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [154]:
np.split(a, 3, 0)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [155]:
np.split(a, [3,6,9], 0)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [156]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [157]:
np.vsplit(b, 2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [158]:
np.split(b, 2, 0)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [159]:
np.hsplit(b, [1])

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [160]:
np.split(b, [1], 1)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [161]:
# 3.1.12 검색
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [162]:
np.where(a > 15)

(array([6, 7, 8, 9]),)

In [164]:
np.where(a > 15, 1, 0)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [165]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [166]:
np.where(a>15, 99, a)

array([10, 11, 12, 13, 14, 15, 99, 99, 99, 99])

In [167]:
np.where(a>15, a, 0)

array([ 0,  0,  0,  0,  0,  0, 16, 17, 18, 19])

In [168]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [169]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
coords = np.where(b>6)
coords

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [171]:
np.stack( (coords[0], coords[1]), -1)

array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]])

In [172]:
z = np.array([0,1,2,0,1,2])
np.nonzero(z)

(array([1, 2, 4, 5]),)

In [173]:
zz = np.array([[0,1,2], [1,2,0], [2,0,1]])
zz

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]])

In [174]:
coords = np.nonzero(zz)
coords

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 1, 0, 2]))

In [175]:
np.stack( (coords[0], coords[1]), -1)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 2]])

In [176]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [177]:
np.nonzero(a>15)

(array([6, 7, 8, 9]),)

In [178]:
np.where(a>15)

(array([6, 7, 8, 9]),)

In [179]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [180]:
np.nonzero(b>6)

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [181]:
np.where(b>6)

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [182]:
t = np.array([True, True, True])
np.all(t)

np.True_

In [183]:
t[1] = False
t

array([ True, False,  True])

In [184]:
np.all(t)

np.False_

In [185]:
tt = np.array([[True, True], [False, True], [True, True]])
tt

array([[ True,  True],
       [False,  True],
       [ True,  True]])

In [186]:
np.all(tt, 0)

array([False,  True])

In [187]:
np.all(tt, 1)

array([ True, False,  True])

In [188]:
a = np.arange(10)
b = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [189]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [191]:
np.all(a==b)

np.True_

In [192]:
b[5] = -1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
b

array([ 0,  1,  2,  3,  4, -1,  6,  7,  8,  9])

In [194]:
np.all(a==b)

np.False_

In [195]:
np.where(a==b)

(array([0, 1, 2, 3, 4, 6, 7, 8, 9]),)

In [196]:
np.where(a!=b)

(array([5]),)

In [197]:
# 3.1.13 기초 통계 함수
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
np.sum(a)

np.int64(66)

In [199]:
np.sum(a, 0)

array([12, 15, 18, 21])

In [200]:
np.sum(a, 1)

array([ 6, 22, 38])

In [201]:
np.mean(a)

np.float64(5.5)

In [202]:
np.mean(a, 0)

array([4., 5., 6., 7.])

In [203]:
np.mean(a, 1)

array([1.5, 5.5, 9.5])

In [204]:
np.amin(a)

np.int64(0)

In [205]:
np.amin(a, 0)

array([0, 1, 2, 3])

In [206]:
np.amin(a, 1)

array([0, 4, 8])

In [207]:
np.amax(a)

np.int64(11)

In [208]:
np.amax(a, 0)

array([ 8,  9, 10, 11])

In [209]:
np.amax(a, 1)

array([ 3,  7, 11])

In [210]:
np.amin is np.min

False

In [211]:
np.max is np.amax

False

In [213]:
np.amax

<function amax at 0x0000029774DCD2B0>