#### 【 규제 Layer - Dropout 】
- 모델의 과대적합을 위한 규제 층
- 출력값에 지정된 비율(p)만큼 0으로 처리해 주는 층

In [1]:
##- 모듈 로딩
import torch
import torch.nn as nn

In [4]:
##- 2개 Layer 생성
fcLAY   = nn.Linear(4, 4)
dropLAY = nn.Dropout(p=0.5)

##- 테스트용 텐서 생성
x = torch.randn(2, 4)

print(x)

tensor([[ 0.0678, -0.5714,  0.8309,  0.3245],
        [ 0.3232,  1.8971, -0.3522,  0.4474]])


In [5]:
##- 가중합 계산 + 활성화함수
zTS = fcLAY(x)
aTS = torch.relu(zTS)

print(f'zTS ===>\n{zTS}\n\naTS =>\n{aTS}')

zTS ===>
tensor([[-0.6252,  0.8202, -0.4063,  0.7352],
        [ 0.1470, -0.1415,  0.2065, -0.7983]], grad_fn=<AddmmBackward0>)

aTS =>
tensor([[0.0000, 0.8202, 0.0000, 0.7352],
        [0.1470, 0.0000, 0.2065, 0.0000]], grad_fn=<ReluBackward0>)


In [6]:
##- [규제 Dropout] ----------------------------------------
##- 일부 출력값 0처리
##- W도 없고, b도 없음
##- 선형결합(가중합)을 절대 하지 않음
##- 이미 계산된 activation에 마스크만 곱함
##- ------------------------------------------------------
outTS = dropLAY(aTS)
print(f'aTS ===>\n{aTS}\n\noutTS =>\n{outTS}')

aTS ===>
tensor([[0.0000, 0.8202, 0.0000, 0.7352],
        [0.1470, 0.0000, 0.2065, 0.0000]], grad_fn=<ReluBackward0>)

outTS =>
tensor([[0.0000, 1.6404, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]], grad_fn=<MulBackward0>)


In [7]:
## ------------------------------------------------------
## 학습 중(training):
## ------------------------------------------------------
print(f'aTS ===>\n{aTS}')

p     = 0.4
mask  = (torch.rand_like(aTS) > p).float()
print(f'mask  ===>\n{mask}')

outTS = aTS * mask / (1 - p)
print(f'outTS ===>\n{outTS}')

aTS ===>
tensor([[0.0000, 0.8202, 0.0000, 0.7352],
        [0.1470, 0.0000, 0.2065, 0.0000]], grad_fn=<ReluBackward0>)
mask  ===>
tensor([[0., 1., 1., 1.],
        [0., 0., 0., 1.]])
outTS ===>
tensor([[0.0000, 1.3670, 0.0000, 1.2254],
        [0.0000, 0.0000, 0.0000, 0.0000]], grad_fn=<DivBackward0>)


In [ ]:
## ------------------------------------------------------
## 평가 시(eval): 입력 받은 Tensor --> 그대로 출력
## ------------------------------------------------------
outTS = aTS     # 아무것도 안 함