### 【 Tensor 객체 생성 】
- 일반 텐서 : torch.tensor(), zeros(), ones(), full(), eye()
- 난수 텐서 : torch.rand(), randn(), randint()
- 텐서 생성자 : torch.FloatTensor(), IntTensor(), BoolTensor(), Tensor()

In [1]:
## 모듈 로딩
import torch        #- 텐서 및 기본 연산관련 함수들 존재

In [16]:
## ----------------------------------------------------------------
## 기___능 : 텐서 정보 출력 함수
## 이___름 : printInfo
## 매개변수 : tensor, tname
## 반환결과 : 없음
## ----------------------------------------------------------------
def printInfo(tensor, tname):
    print(f"----[{tname} 정보]\n")
    print(f"- shape  : {tensor.shape}")
    print(f"- ndim   : {tensor.ndim}D")
    print(f"- dtype  : {tensor.dtype}")
    print(f"- device : {tensor.device}")
    print(f"- data   :\n{tensor}")

In [ ]:
## ===========================================
## 텐서 생성하기- (1) 일반 텐서 + 타입 설정
##              [기] requires_grad=False->True
## ===========================================
DEVICE = "cuda" if torch.cuda.is_available() else 'cpu'

t0 = torch.tensor(10., requires_grad=True)
t1 = torch.tensor([11,22])
t2 = torch.tensor([[11.,22.,33],[44.,55,66]], requires_grad=True)

## -> 텐서별 정보 출력
printInfo(t0, "t0")
printInfo(t1, "t1")
printInfo(t2, "t2")

----[t0 정보]

- shape  : torch.Size([])
- ndim   : 0D
- dtype  : torch.float32
- device : cpu
- data   :
10.0
----[t1 정보]

- shape  : torch.Size([2])
- ndim   : 1D
- dtype  : torch.int64
- device : cpu
- data   :
tensor([11, 22])
----[t2 정보]

- shape  : torch.Size([2, 3])
- ndim   : 2D
- dtype  : torch.float32
- device : cpu
- data   :
tensor([[11., 22., 33.],
        [44., 55., 66.]], requires_grad=True)


In [ ]:
## ============================================
## 텐서 생성하기- (1) 일반 텐서 + 업데이트 여부 설정
## ============================================
import pandas as pd

## - DataFrame, Series 객체 생성
df = pd.DataFrame([[11,22,33],[44,55,66]])
sr = df[0]

## - DataFrame, Series 객체 ===> ndarray ==> Tensor 변환
dfT = torch.tensor(df.values)
srT = torch.tensor(sr.values)

array([[11, 22, 33],
       [44, 55, 66]])