### 【 ANN 모델 구성 】

- 기본구성 : 입력층 - 은닉층 - 출력층
- Linear Layer 클래스
    - 퍼셉트론의 가중치합계 기능처리 클래스
    - 입력값으로 피쳐 수
    - 출력값으로 출력 수 ==> 층의 퍼셉트론 개수
- nn.Module 클래스
    - 커스텀 모델 구현을 위한 부모 클래스

[1] 모듈 로딩 <hr>

In [1]:
import torch                            ## 텐서 및 수치함수들
import torch.nn as nn                   ## 인공신경망 모듈
import torch.nn.functional as F         ## 인공신경망 관련 함수들 모듈

[2] 모델 설계 <hr>

In [2]:
## ---------------------------------------------------------------- 
## 주제 : 거리, 신호, 날씨에 따른 도착시간 예측 모델
## 피쳐 : 거리, 신호, 날씨  3개
## 타겟 : 도착시간         1개
## 종류 : 지도학습 + 회귀
## ---------------------------------------------------------------- 
##           입력  퍼셉트론  출력      활성함수
## 입력층      3     10      10        ReLU 
##            _______________|
##            ↓
## 은닉층     10      5       5        ReLU
##            _______________|
##            ↓
## 출력층      5      1       1         - 회귀로 활성함수 X
## ----------------------------------------------------------------
## 클래스이름 : ANNModel
## 부모클래스 : nn.Module
## 오바라이딩 : _ _init_ _()  : 모델 층 구성
##            forawrd( )    : 순방향 학습
## ----------------------------------------------------------------
class ANNModel(nn.Module):

    ## 모델 층 구성 및 초기화 메서드
    def __init__(self):
        super().__init__()
        self.in_layer = nn.Linear(3, 10)
        self.hd_layer = nn.Linear(10, 5)
        self.ot_layer = nn.Linear(5, 1)

    
    ## 순방향 진행 메서드
    def forward(self, x):
        ## 입력층 => 가중치합계 => AF
        out = self.in_layer(x)
        out = F.relu(out)

        ## 은닉층 => 가중치합계 => AF
        out = self.hd_layer(out)
        out = F.relu(out)

        ## 출력층 => 가중치합계 Because .회귀
        out = self.ot_layer(out)
        return out

In [3]:
## 모델 인스턴스 생성
model = ANNModel()
model

ANNModel(
  (in_layer): Linear(in_features=3, out_features=10, bias=True)
  (hd_layer): Linear(in_features=10, out_features=5, bias=True)
  (ot_layer): Linear(in_features=5, out_features=1, bias=True)
)

In [6]:
## 층별 생성 된 파라미터들(W, b)확인
for name, param in model.named_parameters():
    print(f'[{name}]======{param.shape}')
    print(param)

[in_layer.weight]======torch.Size([10, 3])
Parameter containing:
tensor([[-0.4968, -0.2789,  0.4150],
        [ 0.5373,  0.4607, -0.1550],
        [ 0.1584, -0.3925, -0.3129],
        [ 0.2036, -0.1296,  0.0524],
        [ 0.3643, -0.2984, -0.0691],
        [ 0.4469,  0.3703,  0.2578],
        [ 0.0534, -0.4747,  0.3649],
        [-0.1682, -0.4398,  0.0638],
        [-0.5555,  0.1384,  0.0708],
        [ 0.5459,  0.1480,  0.3239]], requires_grad=True)
[in_layer.bias]======torch.Size([10])
Parameter containing:
tensor([-0.5748, -0.2063, -0.3622, -0.0283,  0.2000, -0.1947, -0.0790, -0.3277,
        -0.1608,  0.2248], requires_grad=True)
[hd_layer.weight]======torch.Size([5, 10])
Parameter containing:
tensor([[ 0.3075,  0.2553,  0.0652,  0.1668,  0.0860, -0.1856,  0.0287, -0.1089,
          0.0936,  0.0592],
        [ 0.2754,  0.1690, -0.3092,  0.0154,  0.2207,  0.0678, -0.1415, -0.1011,
          0.1243, -0.2109],
        [ 0.0674,  0.1581, -0.1822,  0.0029, -0.1553,  0.0970,  0.0746,  0

In [8]:
## 임의의 데이터 : 랜덤 => 샘플 수 5개, 피쳐 3개
torch.manual_seed(10)

feature = torch.randint(1, 10, (5, 3))
feature = feature.type(torch.float32)
feature

tensor([[6., 4., 7.],
        [5., 7., 3.],
        [9., 8., 5.],
        [4., 6., 3.],
        [2., 6., 9.]])

In [9]:
## => 순전파 진행 : 모델변수명(텐사데이터)
model(feature)

tensor([[0.4063],
        [0.5239],
        [0.8112],
        [0.4070],
        [0.2830]], grad_fn=<AddmmBackward0>)