#### 【 ndarray 객체 생성 】

In [19]:
# 모듈 로딩
import numpy as np

In [20]:
## ===================================================
## 함수 : numpy.zeros(shape, 0) : [기본] float
## ===================================================
## numpy ndarray객체 생성
nparray01=np.zeros((2,3))


## ndarray 속성
print('type(nparray01)       =', type(nparray01))
print('nparray01.shape       =', nparray01.shape)
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (2, 3)
nparray01.size        = 6
nparray01.itemsize    = 8
nparray01.dtype       = float64
[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
## numpy ndarray객체 생성
nparray01=np.zeros((5,))


## ndarray 속성
print('type(nparray01)       =', type(nparray01))
print('nparray01.shape       =', nparray01.shape)
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (5,)
nparray01.size        = 5
nparray01.itemsize    = 8
nparray01.dtype       = float64
[0. 0. 0. 0. 0.]


In [22]:
## ===================================================
## 함수 : numpy.ones(shape, 1) : 기본 float
## ===================================================
## numpy ndarray객체 생성
nparray01=np.zeros((2, 3, 1, 2))


## ndarray 속성
print('type(nparray01)       =', type(nparray01))
print('nparray01.shape       =', nparray01.shape)
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (2, 3, 1, 2)
nparray01.size        = 12
nparray01.itemsize    = 8
nparray01.dtype       = float64
[[[[0. 0.]]

  [[0. 0.]]

  [[0. 0.]]]


 [[[0. 0.]]

  [[0. 0.]]

  [[0. 0.]]]]


In [23]:
## numpy ndarray객체 생성 3행 2열
nparray01=np.array([[11,22], [33,44], [55,66]]) 


## ndarray 속성
print('type(nparray01)       =', type(nparray01))
print('nparray01.shape       =', nparray01.shape)
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (3, 2)
nparray01.size        = 6
nparray01.itemsize    = 8
nparray01.dtype       = int64
[[11 22]
 [33 44]
 [55 66]]


In [27]:
## ======================================
## numpy.full(shape, n) : [기본] float
## ======================================
nparray01 = np.full((2,3), 7)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (2, 3)
nparray01.size        = 6
nparray01.itemsize    = 8
nparray01.dtype       = int64
[[7 7 7]
 [7 7 7]]


In [28]:
## ===================================================
## 함수 : numpy.zeros_like(ndarray객체) : [기본] float
## ===================================================
## numpy ndarray객체 생성
a = np.array([11,22])
nparray01=np.zeros_like(a)


## ndarray 속성
print('type(nparray01)       =', type(nparray01))
print('nparray01.shape       =', nparray01.shape)
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (2,)
nparray01.size        = 2
nparray01.itemsize    = 8
nparray01.dtype       = int64
[0 0]


In [26]:
## ===================================================
## 함수 : numpy.zeros_like(ndarray객체) : [기본] float
## 함수 : numpy.ones_like(ndarray객체) : [기본] float
## ===================================================
## numpy ndarray객체 생성
a = np.array([11,22])
nparray01=np.zeros_like(a)
nparray02=np.ones_like(a)


## ndarray 속성
print('type(nparray01)       =', type(nparray01))
print('nparray01.shape       =', nparray01.shape)
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

## ndarray 속성
print('type(nparray02)       =', type(nparray02))
print('nparray02.shape       =', nparray02.shape)
print('nparray02.size        =', nparray02.size)        ## 원소 개수
print('nparray02.itemsize    =', nparray02.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray02.dtype       =', nparray02.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (2,)
nparray01.size        = 2
nparray01.itemsize    = 8
nparray01.dtype       = int64
[0 0]
type(nparray02)       = <class 'numpy.ndarray'>
nparray02.shape       = (2,)
nparray02.size        = 2
nparray02.itemsize    = 8
nparray02.dtype       = int64
[0 0]


In [ ]:
## ===================================================
## 함수 : numpy.arange([start,] stop [, step]) : 1D ndarray
##       [기] start = 0, step = 1
## ===================================================
## numpy ndarray객체 생성
nparray01 = np.arange(5)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))
print('nparray01.shape       =', nparray01.shape)
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (5,)
nparray01.size        = 5
nparray01.itemsize    = 8
nparray01.dtype       = int64
[0 1 2 3 4]


In [30]:
## ===================================================
## 함수 : numpy.arange([start,] stop [, step]) : 1D ndarray
##       [기] start = 0, step = 1
## ===================================================
## numpy ndarray객체 생성
nparray01 = np.arange(2, 10, 3)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))
print('nparray01.shape       =', nparray01.shape)
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (3,)
nparray01.size        = 3
nparray01.itemsize    = 8
nparray01.dtype       = int64
[2 5 8]
