####  【 ndarray 원소 다루기 】
- 인덱싱
    * 변수명[인덱스] / 변수명[행인덱스][열인덱스]
    
- 슬라이싱
    * 변수명[시작인덱스   : 끝인덱스  : 간격]
    * 변수명[행시작인덱스 : 행끝인덱스 : 간격, 열시작인덱스 : 열끝인덱스 : 간격]
    * 범위 : 시작인덱스<= ~ < 끝인덱스

In [ ]:
## =======================================
## 모듈 로딩
## =======================================
import numpy as np

In [2]:
## =======================================
## 1) 1차원 인덱싱/슬라이싱
## =======================================
## 데이터 준비
b = np.array([10, 20, 30, 40, 50])
#              0   1   2   3   4

print("b[0]        =", b[0])             # 10 (첫 원소)
print("b[-1]       =", b[-1])            # 50 (뒤에서 첫 원소)
print("b[1:4]      =", b[1:4])           # 슬라이스 [20,30,40)
print("b[:3]       =", b[:3])            # 처음~2 인덱스까지
print("b[::2]      =", b[::2])           # step=2
print("b[::-1]     =", b[::-1], '\n')    # 역순

b[0]        = 10
b[-1]       = 50
b[1:4]      = [20 30 40]
b[:3]       = [10 20 30]
b[::2]      = [10 30 50]
b[::-1]     = [50 40 30 20 10] 



In [ ]:
## =======================================
## 1) 1차원 인덱싱/슬라이싱
## =======================================
## 데이터 준비
a = np.array([  [1, 2,  3, 4],
                [5, 6,  7, 8],
                [9, 10, 11, 12]])

# 열/컬럼 선택시 => 변수명 [:, 열인덱스]
print("a[0]         =", a[0])                #0번째 행
print("a[:, 1]      =", a[:, 1])             # 1번째 열 (모든 행)
print("a[1:3, 2:] =\n", a[1:3, 2:], '\n')    # 부분 행렬

# 행/열 뒤집기
print("행 역순 a[::-1]  =\n", a[::-1],   '\n')
print("열 역순 a[:,::-1]=\n", a[:,::-1], '\n')

a[0]         = [1 2 3 4]
a[:, 1]      = [ 2  6 10]
a[1:3, 2:] =
 [[ 7  8]
 [11 12]] 

행 역순 a[::-1]  =
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]] 

열 역순 a[:,::-1]=
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]] 



In [ ]:
## =======================================
## 3) Fancy 인덱싱(정수 배열/리스트로 선택)
##    - 불연속/불규칙적인 임의의 데이터 추출
##    - 형식 : 변수명[ [행번호 리스트] ]
## =======================================
## 데이터 준비
a = np.array([  [1, 2,  3, 4],
                [5, 6,  7, 8],
                [9, 10, 11, 12]])

## 추출 변수
rows, cols = [0, 2], [1, 0]

## => 여러 개 행 추출
print(a)
print('----------------')
print("a[rows]  =>\n", a[rows])     ## a[ [0, 2] ]
print()

## => 여러 개 컬럼 추출
print(a)
print('----------------')
print("a[cols]  =>\n", a[:, cols])  ## a[:, [1, 0]]
print()


## 같은 위치 쌍 선택 : a[ [0,2], [1,0] ] => a[0, 1], a[2, 0]
print(a)
print('----------------')
print("a[rows, cols]  =>\n", a[rows, cols])   ## a[ [0,2], [1,0] ]


## 행,열 조합의 격자 선택 : np.ix_(rows,cols),  a[np.idx_( [0, 2],[1, 0])]
print(a)
print('----------------')
print("a[np.ix_(rows,cols)]  =>\n", a[np.ix_(rows, cols)]) 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------
a[rows]  =>
 [[ 1  2  3  4]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------
a[cols]  =>
 [[ 2  1]
 [ 6  5]
 [10  9]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------
a[rows, cols]  =>
 [2 9]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------
a[np.ix_(rows,cols)]  =>
 [[ 2  1]
 [10  9]]


In [ ]:
# --------------------------------------
# 불리언 마스크
# --------------------------------------